name: BLS Data Update

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st day of each month
  workflow_dispatch:       # Allows manual triggering

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the Data Collection Script
      - name: Run Data Collection Script
        run: python BLS_data_collection.py

      # Commit and Push Updated Data
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add BLS_data.csv

          if git status | grep -q "Changes to be committed"; then
            git commit -m "Automated BLS Data Update - $(date)"
            git push https://x-access-token:${{ secrets.API_KEY }}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi
